#!/bin/bash

APP_KEY= DB_DATABASE= DB_USERNAME= DB_PASSWORD= MAIL_USERNAME= MAIL_PASSWORD= AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= LOG_DISCORD_WEBHOOK_URL= docker stack deploy -c production.docker-compose.yml archelp
